services:
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  kora:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./kora.toml:/app/kora.toml
      - ./.env:/app/.env:ro
    environment:
      - RUST_LOG=info
    env_file:
      - .env
    command:
      - sh
      - -c
      - 'kora-rpc --config /app/kora.toml --private-key "$$KORA_PRIVATE_KEY"'
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  redis_data:
