services:
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf

  kora:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./kora.toml:/app/kora.toml
      - ./signers.toml:/app/signers.toml
      - ./.env:/app/.env:ro
    environment:
      - RUST_LOG=info
    env_file:
      - .env
    command:
      - sh
      - -c
      - "kora --config /app/kora.toml --rpc-url ${RPC_URL:-http://127.0.0.1:8899} rpc start --signers-config /app/signers.toml"
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  redis_data:
