name: Bug Report
description: Report a bug with Kora
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug. Include steps to reproduce if possible.
    validations:
      required: true

  - type: input
    id: kora-version
    attributes:
      label: Kora version
      description: "Output of `kora --version` or the crate version from Cargo.toml"
      placeholder: "e.g. 2.0.4"
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: SDK version
      description: "If using the TypeScript SDK, which version? N/A if not using."
      placeholder: "e.g. 0.1.3 or N/A"
    validations:
      required: false

  - type: dropdown
    id: signer-type
    attributes:
      label: Signer type
      options:
        - Memory (local keypair)
        - Turnkey
        - Privy
        - Vault
        - No signer
        - Other
        - N/A
    validations:
      required: false

  - type: dropdown
    id: solana-cluster
    attributes:
      label: Solana cluster
      options:
        - mainnet
        - devnet
        - localnet
        - custom
    validations:
      required: false

  - type: checkboxes
    id: public-rpc
    attributes:
      label: RPC endpoint
      options:
        - label: "Check box if using a public endpoint (e.g. `https://api.devnet.solana.com`)" (not recommended for production)

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or errors
      description: Paste any error output, logs, or stack traces. Run with `RUST_LOG=debug` for more detail.
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration (optional)
      description: "Relevant parts of your `kora.toml` (redact secrets)."
      render: toml
    validations:
      required: false
