name: Feature Request
description: Suggest a feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe the feature and the problem it solves.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches you've thought about.
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - RPC Server
        - Transaction handling
        - Signer integrations
        - Configuration
        - TypeScript SDK
        - CLI
        - Documentation
        - Other
    validations:
      required: false
