[kora]
rate_limit = 100
# Optional: Payment address to receive payment tokens (defaults to signer address)
# payment_address = "YourPaymentAddressPubkey11111111111111111111"

[kora.cache]
enabled = false
default_ttl = 300
account_ttl = 60

[kora.enabled_methods]
liveness = false
estimate_transaction_fee = true
get_supported_tokens = true
sign_transaction = true
sign_and_send_transaction = true
transfer_transaction = true
get_blockhash = true
get_config = true
sign_transaction_if_paid = true
get_payer_signer = true

[validation]
max_allowed_lamports = 1000000
max_signatures = 10
price_source = "Mock"
allowed_programs = [
    "11111111111111111111111111111111",             # System Program
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",  # Token Program
    "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL", # Associated Token Program
    "AddressLookupTab1e1111111111111111111111111",  # Address Lookup Table Program
    "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr",  # Memo Program
    "ComputeBudget111111111111111111111111111111", # Compute Budget Program
]
allowed_tokens = [
    "9BgeTKqmFsPVnfYscfM6NvsgmZxei7XfdciShQ6D3bxJ", # Update this based on the USDC_LOCAL_KEY public key comment in your .env
]
allowed_spl_paid_tokens = [
    "9BgeTKqmFsPVnfYscfM6NvsgmZxei7XfdciShQ6D3bxJ", # Update this based on the USDC_LOCAL_KEY public key comment in your .env
]

disallowed_accounts = [
    "hndXZGK45hCxfBYvxejAXzCfCujoqkNf7rk4sTB8pek", # Test disallowed account for lookup table
]

[validation.fee_payer_policy]
allow_sol_transfers = true
allow_spl_transfers = true
allow_token2022_transfers = true
allow_assign = true
allow_burn = true
allow_close_account = true
allow_approve = true

[validation.price]
type = "margin" # free / margin / fixed
margin = 0.1  # Default margin (10%) for paid transaction validation


[validation.token2022]
blocked_mint_extensions = [
    # "confidential_transfer_mint",     # Confidential transfer configuration for the mint
    # "confidential_mint_burn",         # Confidential mint and burn configuration
    # "transfer_fee_config",            # Transfer fee configuration
    # "mint_close_authority",           # Authority allowed to close the mint
    # "interest_bearing_config",        # Interest-bearing token configuration
    # "non_transferable",               # Makes tokens non-transferable
    # "permanent_delegate",             # Permanent delegate for the mint
    # "transfer_hook",                  # Block tokens with transfer hooks
    # "pausable",                       # Block pausable tokens
]
blocked_account_extensions = [
    # "confidential_transfer_account", # Confidential transfer state for the account
    # "non_transferable_account",      # Non-transferable token account
    # "transfer_hook_account",          # Transfer hook state for the account
    # "pausable_account",               # Pausable token account state
    # "memo_transfer",                  # Requires memo for transfers
    # "cpi_guard",                      # Prevents certain CPI calls
    # "immutable_owner",                # Account owner cannot be changed
    # "default_account_state",          # Default state for new accounts
]

[kora.usage_limit]
enabled = false
cache_url = "redis://redis:6379"
max_transactions = 2
fallback_if_unavailable = false