name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '**.txt'
      - 'LICENSE*'
      - '.gitignore'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '**.txt'
      - 'LICENSE*'
      - '.gitignore'

jobs:
  rust-ci:
    uses: ./.github/workflows/rust.yml
    secrets: inherit

  typescript-integration:
    uses: ./.github/workflows/typescript-integration.yml
    secrets: inherit

  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [rust-ci, typescript-integration]
    if: always()
    steps:
      - name: Check all jobs status
        run: |
          if [[ "${{ needs.rust-ci.result }}" != "success" ]]; then
            echo "❌ Rust CI failed"
            exit 1
          fi
          if [[ "${{ needs.typescript-integration.result }}" != "success" ]]; then
            echo "❌ TypeScript integration tests failed"
            exit 1
          fi
          echo "✅ All CI checks passed!"