name: Kora Privy Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'crates/privy-rs/**'
      - 'Cargo.toml'
      - 'rust-toolchain.toml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Build check
        working-directory: crates/privy-rs
        run: cargo build
      
      - name: Publish kora-privy crate
        working-directory: crates/privy-rs
        run: cargo publish --locked --token ${{ secrets.KORA_PRIVY_REGISTRY_TOKEN }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.KORA_PRIVY_REGISTRY_TOKEN }} 